version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: license_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: license_db
      MYSQL_USER: license_user
      MYSQL_PASSWORD: license_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
